xgb_params = {
    "max_depth": 4,
    "eta": 0.01,
    "objective": "reg:squarederror",
    "eval_metric": ["rmse"],
    "booster": "gbtree",
    "verbosity": 0,
    "sample_type": "weighted",
    "max_delta_step": 4,
    "subsample": 0.5,
    "min_child_weight": 100,
    "early_stopping_round": 50,
}

lgbm_params = {
    "bagging_freq": 5,
    "bagging_fraction": 0.6,
    "bagging_seed": 123,
    "boost_from_average": "false",
    "boost": "gbdt",
    "feature_fraction": 0.3,
    "learning_rate": 0.005,
    "max_depth": 3,
    "metric": "rmse",
    "num_leaves": 128,
    "num_threads": 8,
    "tree_learner": "serial",
    "objective": "regression",
    "verbosity": -1,
    "random_state": 123,
    "max_bin": 8,
    "early_stopping_round": 100,
}

style = {
    "axes.axisbelow": True,
    "axes.edgecolor": ".8",
    "axes.facecolor": "white",
    "axes.grid": True,
    "axes.labelcolor": ".15",
    "axes.spines.bottom": True,
    "axes.spines.left": True,
    "axes.spines.right": True,
    "axes.spines.top": True,
    "figure.facecolor": "white",
    "font.family": ["sans-serif"],
    "font.sans-serif": [
        "Arial",
        "DejaVu Sans",
        "Liberation Sans",
        "Bitstream Vera Sans",
        "sans-serif",
    ],
    "grid.color": ".8",
    "grid.linestyle": "--",
    "image.cmap": "dark",
    "lines.solid_capstyle": "round",
    "patch.edgecolor": "w",
    "patch.force_edgecolor": True,
    "text.color": ".15",
    "xtick.bottom": False,
    "xtick.color": ".15",
    "xtick.direction": "out",
    "xtick.top": False,
    "ytick.color": ".15",
    "ytick.direction": "out",
    "ytick.left": False,
    "ytick.right": False,
}
